// Ported from ShipLine src/components/payments/paymentsFlowMath.ts @ 77577a1 — changes: the model is one transpiled file, ./model.js (today required; dateOfInstant pinned to Europe/London; buildPaymentsFlow(input, {claims: true}) also returns balanceClaims — without the option the output is the TS's); the modules by concern re-export it; new, not in the TS: ids.js (feed ids) and forecast.js (feed rows)
'use strict';

// Payments-flow model — "what money leaves the account, to whom, when" for
// stock purchase orders. A CommonJS port of ShipLine's
// src/components/payments/paymentsFlowMath.ts at commit 77577a1 (2026-10-06;
// JFlow PHASE2 P1 as amended: the math is ported into this API,
// api/src/lib/payments-flow/, and re-synced with the oracle when ShipLine's
// math changes — re-pinned from f9499bc on 2026-10-06). Pure: no database, no
// network, no clock.
//
// Identical to the TS (proved by api/test/unit/payments-flow-golden.test.js
// against the frozen TS itself, whose output api/tools/payments-flow-oracle.mjs
// records) except, deliberately:
//   1. buildPaymentsFlow requires input.today — no localTodayYmd() fallback.
//   2. dateOfInstant is pinned to Europe/London, not the host's zone.
//   3. buildPaymentsFlow(input, { claims: true }) also returns balanceClaims
//      (step 18, for the JFlow feed); without the option nothing changes.
// ids.js (feed ids, PHASE2 §3 P2) and forecast.js (the JFlow feed rows) are
// new; they read the model's output and add nothing to it.
//
// Modules:
//   model       THE model: the TS transpiled whole (generated by the re-pin
//               script; never hand-edited), requiring only keys and containers
//   keys        ShipLine paymentReviews.ts key builders (deposit:, balance:, item:, qc:)
//   containers  ShipLine containerHelpers: live-tracking lookup, internal numbers
//   dates, lines, money, terms, suppliers, policy, due, po, overrides, flow
//               thin re-exports of model.js, by concern
//   ids         feed ids
//   forecast    JFlow feed rows: open items, QC units, extras, payments made
//   types       JSDoc types only
// Display-only exports of the TS (bucketize, fmtYmd, describePolicy, the KPI
// windows…) ride along in model.js and are unused here.

const { dateOf, dateOfInstant, addDays } = require('./dates');
const { LANDED_STATUSES } = require('./lines');
const { describeRule, parsePaymentTerms, resolveTermsRule } = require('./terms');
const { indexSuppliersByName, isLegacySupplier, matchSupplier } = require('./suppliers');
const { AIR_LIMIT_DEFAULT_DAYS, EMPTY_PAYMENT_RULE_ESTIMATES, resolvePolicy, canonicalizeRules } = require('./policy');
const { buildPoChain, freightModeOf, indexOpenContainers } = require('./due');
const { summarizePo } = require('./po');
const { CURRENCY_ORDER, buildPaymentsFlow } = require('./flow');
const { depositKey, balanceKey, itemKey, dueOverrideKeys, applyDueOverrides } = require('./overrides');
const { qcInvoiceKey } = require('./keys');
const { EXTRA_KIND_LABEL } = require('./model');
const { FEED_ID_RE, isFeedId, groupToken, partToken, parseTsId, feedId, itemFeedId } = require('./ids');
const {
    TEXT_LIMITS, shipmentIdOf, poDirectory, collectPaidRows, splitCents, formatCents, dueSetOf, toForecastRows,
} = require('./forecast');

module.exports = {
    // model
    buildPaymentsFlow, summarizePo,
    // terms, suppliers, policy
    parsePaymentTerms, resolveTermsRule, describeRule,
    indexSuppliersByName, isLegacySupplier, matchSupplier,
    resolvePolicy, canonicalizeRules, buildPoChain, freightModeOf,
    // dates
    dateOf, dateOfInstant, addDays,
    // constants
    LANDED_STATUSES, CURRENCY_ORDER, AIR_LIMIT_DEFAULT_DAYS, EMPTY_PAYMENT_RULE_ESTIMATES, EXTRA_KIND_LABEL,
    // drafts and plans
    indexOpenContainers,
    // due dates set by hand, sign-off keys
    depositKey, balanceKey, itemKey, qcInvoiceKey, dueOverrideKeys, applyDueOverrides,
    // feed ids
    FEED_ID_RE, isFeedId, groupToken, partToken, parseTsId, feedId, itemFeedId,
    // JFlow feed
    TEXT_LIMITS, shipmentIdOf, poDirectory, collectPaidRows, splitCents, formatCents, dueSetOf, toForecastRows,
};
